// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createSubmissionStmt, err = db.PrepareContext(ctx, createSubmission); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSubmission: %w", err)
	}
	if q.getFormSubmissionContextStmt, err = db.PrepareContext(ctx, getFormSubmissionContext); err != nil {
		return nil, fmt.Errorf("error preparing query GetFormSubmissionContext: %w", err)
	}
	if q.incrementStorageUsageStmt, err = db.PrepareContext(ctx, incrementStorageUsage); err != nil {
		return nil, fmt.Errorf("error preparing query IncrementStorageUsage: %w", err)
	}
	if q.incrementSubmissionCountersStmt, err = db.PrepareContext(ctx, incrementSubmissionCounters); err != nil {
		return nil, fmt.Errorf("error preparing query IncrementSubmissionCounters: %w", err)
	}
	if q.markEmailSentStmt, err = db.PrepareContext(ctx, markEmailSent); err != nil {
		return nil, fmt.Errorf("error preparing query MarkEmailSent: %w", err)
	}
	if q.markWebhookSentStmt, err = db.PrepareContext(ctx, markWebhookSent); err != nil {
		return nil, fmt.Errorf("error preparing query MarkWebhookSent: %w", err)
	}
	if q.updateSubmissionFilesStmt, err = db.PrepareContext(ctx, updateSubmissionFiles); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSubmissionFiles: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createSubmissionStmt != nil {
		if cerr := q.createSubmissionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSubmissionStmt: %w", cerr)
		}
	}
	if q.getFormSubmissionContextStmt != nil {
		if cerr := q.getFormSubmissionContextStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFormSubmissionContextStmt: %w", cerr)
		}
	}
	if q.incrementStorageUsageStmt != nil {
		if cerr := q.incrementStorageUsageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing incrementStorageUsageStmt: %w", cerr)
		}
	}
	if q.incrementSubmissionCountersStmt != nil {
		if cerr := q.incrementSubmissionCountersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing incrementSubmissionCountersStmt: %w", cerr)
		}
	}
	if q.markEmailSentStmt != nil {
		if cerr := q.markEmailSentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markEmailSentStmt: %w", cerr)
		}
	}
	if q.markWebhookSentStmt != nil {
		if cerr := q.markWebhookSentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markWebhookSentStmt: %w", cerr)
		}
	}
	if q.updateSubmissionFilesStmt != nil {
		if cerr := q.updateSubmissionFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSubmissionFilesStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                              DBTX
	tx                              *sql.Tx
	createSubmissionStmt            *sql.Stmt
	getFormSubmissionContextStmt    *sql.Stmt
	incrementStorageUsageStmt       *sql.Stmt
	incrementSubmissionCountersStmt *sql.Stmt
	markEmailSentStmt               *sql.Stmt
	markWebhookSentStmt             *sql.Stmt
	updateSubmissionFilesStmt       *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                              tx,
		tx:                              tx,
		createSubmissionStmt:            q.createSubmissionStmt,
		getFormSubmissionContextStmt:    q.getFormSubmissionContextStmt,
		incrementStorageUsageStmt:       q.incrementStorageUsageStmt,
		incrementSubmissionCountersStmt: q.incrementSubmissionCountersStmt,
		markEmailSentStmt:               q.markEmailSentStmt,
		markWebhookSentStmt:             q.markWebhookSentStmt,
		updateSubmissionFilesStmt:       q.updateSubmissionFilesStmt,
	}
}
