// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Form struct {
	ID                     string         `json:"id"`
	OrganizationID         string         `json:"organization_id"`
	Name                   string         `json:"name"`
	Description            sql.NullString `json:"description"`
	IsActive               bool           `json:"is_active"`
	AllowFileUploads       bool           `json:"allow_file_uploads"`
	MaxFileCount           sql.NullInt32  `json:"max_file_count"`
	MaxFileSize            sql.NullInt32  `json:"max_file_size"`
	AllowedFileTypes       sql.NullString `json:"allowed_file_types"`
	SpamCheckEnabled       bool           `json:"spam_check_enabled"`
	HoneypotFieldName      sql.NullString `json:"honeypot_field_name"`
	ResponseType           string         `json:"response_type"`
	RedirectUrl            sql.NullString `json:"redirect_url"`
	SuccessMessage         sql.NullString `json:"success_message"`
	WebhookUrl             sql.NullString `json:"webhook_url"`
	SendEmailNotifications bool           `json:"send_email_notifications"`
	NotificationEmails     sql.NullString `json:"notification_emails"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              time.Time      `json:"updated_at"`
}

type Member struct {
	ID             string    `json:"id"`
	OrganizationID string    `json:"organization_id"`
	UserID         string    `json:"user_id"`
	Role           string    `json:"role"`
	CreatedAt      time.Time `json:"created_at"`
}

type Organization struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	IsPaused  bool      `json:"is_paused"`
	CreatedAt time.Time `json:"created_at"`
}

type SpaceResourceUsage struct {
	ID                   string    `json:"id"`
	OrganizationID       string    `json:"organization_id"`
	UsedStorageMb        int32     `json:"used_storage_mb"`
	SubmissionsThisMonth int32     `json:"submissions_this_month"`
	TotalSubmissions     int32     `json:"total_submissions"`
	UpdatedAt            time.Time `json:"updated_at"`
}

type Submission struct {
	ID            string                `json:"id"`
	FormID        string                `json:"form_id"`
	Email         sql.NullString        `json:"email"`
	Name          sql.NullString        `json:"name"`
	Status        string                `json:"status"`
	IsRead        bool                  `json:"is_read"`
	IsClosed      bool                  `json:"is_closed"`
	Data          json.RawMessage       `json:"data"`
	Files         pqtype.NullRawMessage `json:"files"`
	IpAddress     sql.NullString        `json:"ip_address"`
	UserAgent     sql.NullString        `json:"user_agent"`
	Referer       sql.NullString        `json:"referer"`
	Device        sql.NullString        `json:"device"`
	DeviceType    sql.NullString        `json:"device_type"`
	Os            sql.NullString        `json:"os"`
	Browser       sql.NullString        `json:"browser"`
	IsRobot       sql.NullBool          `json:"is_robot"`
	IsSpam        sql.NullBool          `json:"is_spam"`
	SpamScore     sql.NullInt32         `json:"spam_score"`
	SpamReason    sql.NullString        `json:"spam_reason"`
	WebhookSent   sql.NullBool          `json:"webhook_sent"`
	WebhookSentAt sql.NullTime          `json:"webhook_sent_at"`
	EmailSent     sql.NullBool          `json:"email_sent"`
	EmailSentAt   sql.NullTime          `json:"email_sent_at"`
	CreatedAt     time.Time             `json:"created_at"`
	UpdatedAt     time.Time             `json:"updated_at"`
	DeletedAt     sql.NullTime          `json:"deleted_at"`
}

type Subscription struct {
	ID                     string    `json:"id"`
	UserID                 string    `json:"user_id"`
	Tier                   string    `json:"tier"`
	Status                 string    `json:"status"`
	MaxSpaces              int32     `json:"max_spaces"`
	MaxSubmissionsPerMonth int32     `json:"max_submissions_per_month"`
	MaxStorageMb           int32     `json:"max_storage_mb"`
	CreatedAt              time.Time `json:"created_at"`
}
