/**
 * Image variant URLs generated by the image processor
 */
export interface ImageVariants {
	thumbnail?: string;
	'thumbnail@2x'?: string;
	regular?: string;
	'regular@2x'?: string;
	// Legacy variants (for backward compatibility)
	small?: string;
	medium?: string;
	large?: string;
}

/**
 * Parse image data that can be either a legacy single URL or JSON with variants
 * @param data - The image field value from the database
 * @returns ImageVariants object (empty if invalid)
 */
export function parseImageVariants(data: string | null | undefined): ImageVariants {
	if (!data) return {};

	// Try to parse as JSON first
	try {
		const parsed = JSON.parse(data);
		if (typeof parsed === 'object' && parsed !== null) {
			return parsed as ImageVariants;
		}
	} catch {
		// Not JSON - could be a legacy single URL
		// Return it as the 'medium' variant for backward compatibility
		return { medium: data };
	}

	return {};
}

/**
 * Get the best image URL for a given size preference
 * Falls back to larger/smaller sizes if preferred size is not available
 *
 * @param variants - Image variants object
 * @param preferredSize - Preferred size (default: 'medium')
 * @returns URL string or undefined
 */
export function getImageUrl(
	variants: ImageVariants | string | null | undefined,
	preferredSize: keyof ImageVariants = 'medium'
): string | undefined {
	const parsed = typeof variants === 'string' ? parseImageVariants(variants) : variants || {};

	// Try preferred size first
	if (parsed[preferredSize]) {
		return parsed[preferredSize];
	}

	// Fallback order based on preferred size
	const fallbackOrder: Partial<Record<keyof ImageVariants, (keyof ImageVariants)[]>> = {
		thumbnail: ['thumbnail@2x', 'regular', 'small', 'medium', 'large'],
		'thumbnail@2x': ['thumbnail', 'regular', 'regular@2x', 'small', 'medium'],
		regular: ['regular@2x', 'medium', 'thumbnail', 'large'],
		'regular@2x': ['regular', 'large', 'medium', 'thumbnail@2x'],
		// Legacy fallbacks
		small: ['medium', 'regular', 'thumbnail', 'large'],
		medium: ['regular', 'large', 'small', 'thumbnail'],
		large: ['regular@2x', 'medium', 'regular', 'small']
	};

	for (const size of fallbackOrder[preferredSize] || []) {
		if (parsed[size]) {
			return parsed[size];
		}
	}

	return undefined;
}

/**
 * Serialize image variants to JSON string for database storage
 */
export function serializeImageVariants(variants: ImageVariants): string {
	return JSON.stringify(variants);
}
